# netlify.toml

[[headers]]
  for = "/*"
  [headers.values]
    # ✅ UPDATED: Added 'unsafe-inline' to script-src and the pixabay URL to img-src
    Content-Security-Policy = "default-src 'self' https://gotravelup-backend.onrender.com; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data: https://res.cloudinary.com https://ia601701.us.archive.org https://cdn.pixabay.com;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"